spring.application.name=open-finance-customer-service

# Config do MongoDB
spring.data.mongodb.host=mongodb-openfinance
spring.data.mongodb.port=27017
spring.data.mongodb.database=openfinance
spring.data.mongodb.username=admin
spring.data.mongodb.password=password
spring.data.mongodb.authentication-database=admin

# Config do server
server.port=8080

# Config de log
logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate=DEBUG
logging.level.com.POC.open_finance_customer_service=DEBUG

# Config AWS LocalStack
aws.endpoint=http://localstack:4566
aws.region=us-east-1
aws.credentials.access-key=test
aws.credentials.secret-key=test